name: ultimatehydrology
channels:
  - conda-forge
  - defaults
dependencies:
  - pygeos=0.12
  - pyproj=3.3.0
  - geopandas=0.10.2
  - joblib=1.1.0
  - numpy=1.21.2
  - pandas=1.3.5
  - pystac=1.2.0
  - pystac-client=0.3.2
  - rasterio=1.2.10
  - requests=2.27.1
  - shapely=1.8.0
  - scikit-learn=1.0.2
  - tqdm=4.62.3
  - urllib3=1.26.7
  - python-wget=3.2
  - rioxarray=0.10.0
  - xarray=0.21.1
  - xgboost=1.5.1
  - catboost=1.0.3
  - lightgbm=3.3.1
  - dask=2022.1.1
  - dask-core=2022.1.1
  - netcdf4=1.5.8
  - bottleneck=1.3.2
  - cfgrib=0.9.10
  - gdal=3.4.0
  - ipython=7.29.0
  - ipykernel=6.4.1
  - richdem=0.3.4
  - jupyter_client=7.1.0
  - jupyter_core=4.9.1
  - jupyter_server=1.4.1
  - jupyterlab=3.2.8
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.10.2
  - jupyterlab_widgets=1.0.2
  - azure-storage-blob==12.13.1
  - ipywidgets=7.6.5
