name: base
channels:
  - conda-forge
  - anaconda
  - pytorch
dependencies:
  - cpuonly
  - python==3.9.10
  - pytorch==1.10.2
  - numpy
  - pandas
  - geos
  - pyproj
  - gdal==3.4.1
  - shapely==1.8.0
  - geopandas==0.10.2
  - rasterio==1.2.10
  - xarray
  - cfgrib==0.9.10.0
  - rioxarray==0.9.1
  - netcdf4==1.5.8
  - dask==2022.1.0
  - s3fs==2022.1.0
  - azure-storage-blob==12.9.0
  - intel-openmp==2022.0.1
  - openblas==0.3.18
  - bottleneck==1.3.2
