name: snow
channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python==3.8.10
  - pip==21.1.3
  - pytorch==1.10.1
  - torchvision==0.11.2
  - cudatoolkit=11.3
  - multiprocess
  - numpy==1.22
  - scikit-learn=1.0.2 
  - pandas==1.3.5
  - geos==3.10.2 
  - pyproj==3.3.0 
  - gdal==3.4.1 
  - shapely==1.8.0
  - geopandas==0.10.2
  - rasterio==1.2.10 
  - xarray==0.20.2
  - cfgrib==0.9.9.0 
  - rioxarray==0.9.1 
  - netcdf4==1.5.8 
  - jupyterlab==3.2.8
  - tqdm==4.62.3
  - omegaconf==2.1.1 
  - einops==0.4.0 
  - ftfy==6.0.3 
  - pillow==8.4.0
  - requests==2.27.1
  - loguru==0.5.3 
  - matplotlib==3.5.1 
  - cartopy==0.20.2
  - python-wget==3.2
  - nodejs==17.1.0
  - dask==2022.1.0
  - s3fs==2022.1.0
  - ipywidgets==7.6.5
  - azure-storage-blob==12.9.0 
  - intel-openmp==2022.0.1
  - openblas==0.3.18 
  - h5py==3.6.0 
  - h5netcdf==0.13.1 
  - tensorboard==2.8.0 
  - matplotlib==3.5.1 
  - seaborn==0.11.2 
  - bottleneck==1.3.2
  # - earthengine-api==0.1.296
  # - folium==0.12.1.post1
  # - sentinelsat==1.1.1 
  # - lightgbm==3.3.2
  # - pip:
  #   - -r file:requirements.txt
